### ISSUE TITLE
'SigmaDetection' object has no attribute 'field'

### ISSUE THREAD

**Issue by xxjiewu** [cyberphor/pySigma-backend-powershell#7]
Running sigma/pipelines/powershell/powershell.py may cause errors on lines 16 and 26.
The error message is: 'SigmaDetection' object has no attribute 'field' (while applying processing pipeline on rule None).
Checking if 'field' exists can avoid errors.
  `if 'field' in detection_item.__dataclass_fields__:`

**Comment by cyberphor** [comment]
thank you! i will try to resolve this issue this weekend.

**Comment by cyberphor** [comment]
added your suggestion, thanks!
